<html>
<head>
<title>async/await is the wrong abstraction - LogRocket Blog</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>async/await是错误的抽象</h1>
<blockquote>原文：<a href="https://blog.logrocket.com/async-await-is-the-wrong-abstraction/#0001-01-01">https://blog.logrocket.com/async-await-is-the-wrong-abstraction/#0001-01-01</a></blockquote><div><article class="article-post">
<p>不可否认的是，<code>async....await</code>模式非常简单，简化了异步编程，更像是服务器端编程，因为没有了<code>try....catch</code>块的保护，开发人员会感到有点不安全和害怕。</p>
<p>我们的意识或左脑在可以被认为是对现实的抽象中运作。宇宙是在同一时间同时发生的一系列无穷小的事件，我们的意识无法理解，它顺序或线性地思考，我们一次处理一个想法。</p>
<p>我们试图用<code>async....await</code>做的是忽略现实，让这些异步操作看起来同步发生。以这种方式逃避现实是很棒的，直到它不再是。</p>
<p>我时常会看到有人发推文，说他们意识到<code>async...await</code>有根本性的缺陷，原因如下……如果你自己没有发现的话。</p>
<blockquote class="embedly-card" data-card-controls="1" data-card-align="center" data-card-theme="light">

<p>没有描述</p>
</blockquote>
<p>当我看到这样的推文时，我感到同情和同情，并相信又有一名成员加入了我们现实世界的搏击俱乐部。我不需要告诉你这个俱乐部的第一条规则是什么。</p>
<p>我第一次意识到这一点是在我开发一个允许用户将大视频文件上传到Azure blob存储的功能时。因为这些文件很大，必须分成独立的块。我在一个<code>for...of</code>循环中使用了<code>async...await</code>。然后出现了用户想要中途取消上传的需求。就在那时，这个神奇的几乎同步的代码块不适合这个目的。</p>
<p>取消承诺链</p>
<h2>这是无法回避的，而且<code>async...await</code>中也完全没有支持取消的东西。下面是从属呼叫链的一个简单示例:</h2>
<p>这里我们有一个经典的承诺链，每个电话都在等待最后一个电话。如果我们想在<code>updateUserAddress</code>取消，不打电话给<code>updateFinancialStatus</code>怎么办？</p>
<pre>async function updatePersonalCircumstances(token) {
  const data = await fetchData();
  const userData = await updateUserData(data);
  const userAddress = await updateUserAddress(userData);
  const financialStatus = await updateFinancialStatus(userAddress);
  
  return financialStatus;
}

const token = {};
const promise = updatePersonalCircumstances(token);</pre>
<p>现在我们已经到了这一部分，你坐得舒服吗？那么让我把它拼出来…..</p>
<p>一旦你打了一个电话，除非潜在的承诺解决或拒绝，否则你永远不会出来。</p>
<p>半生不熟的解决方案</p>
<h2>取消这个链的唯一方法是像这样包装每个单独的<code>async..await</code>调用:</h2>
<p>不幸的是，我们需要检查每个电话，看看是否有取消。我们把做正确事情的全部责任推给了用户。</p>
<pre>async function updatePersonalCircumstances(token) {
  let cancelled = false;

  // we can't reject, since we don't have access to
  // the returned promise
  token.cancel = () =&gt; {
    cancelled = true;
  };

  const data = await wrapWithCancel(fetchData)();
  const userData = await wrapWithCancel(updateUserData)(data);
  const userAddress = await wrapWithCancel(updateUserAddress)(userData);
  const financialStatus = await wrapWithCancel(updateFinancialStatus)(userAddress);

  // we check after each call to see if something has happend
  if (cancelled) {
    throw { reason: 'cancelled' };
  }

  return financialStatus;

  function wrapWithCancel(fn) {
    return data =&gt; {
      if (!cancelled) {
        return fn(data);
      }
    }
  }
}

const token = {};
const promise = updateUser(token);

token.cancel(); // abort!!!</pre>
<p>发电机复兴</p>
<h2>当我第一次遇到这个问题时，我正在做一个angular项目，它有一个依赖项<a href="https://rxjs-dev.firebaseapp.com/" target="_blank" rel="noopener noreferrer"> RxJS </a>。<a href="https://blog.logrocket.com/understanding-rxjs-observables/" target="_blank" rel="noopener noreferrer"> RxJS可观测量</a>对<a href="https://medium.com/the-geeks-of-creately/cancelling-observables-rxjs-f4cf28c3b633" target="_blank" rel="noopener noreferrer">取消</a>有一流支持。rxjs的问题是很难跟上它的速度，它是巨大的。我已经忘记了我所学到的关于rxjs可观测量的大部分内容，但是它们真的很适合取消。要是JavaScript有取消的原生支持就好了？嗯，有点像。</h2>
<p>我最近发现了<a href="https://github.com/thefrontside/effection/tree/master" target="_blank" rel="noopener noreferrer"> effection.js </a>，它是为了解决这个问题而产生的，但后来却拓展了发电机的应用范围。</p>
<p>对于发电机，如果我们想取消，您可以立即返回或丢弃发电机。它实际上是一个没有这种便利的黑盒子。</p>
<p>以下是取消承诺链的更好解决方案:</p>
<p>上面的代码是一个更彻底的例子的基本实现，我在这篇文章的最后链接到这个例子。关键是取消功能:</p>
<pre>function runner(fn, ...args) {
  const gen = fn(...args);
  let cancelled, cancel;
  const promise = new Promise((resolve, promiseReject) =&gt; {
    cancel = () =&gt; {
      cancelled = true;
      reject({ reason: 'cancelled' });
    };
    
    let value;

    onFulfilled();

    function onFulfilled(res) {
      if (!cancelled) {
        let result;
        try {
          result = gen.next(res);
        } catch (e) {
          return reject(e);
        }
        next(result);
        return null;
      }
    }

    function onRejected(err) {
      var result;
      try {
        result = gen.throw(err);
      } catch (e) {
        return reject(e);
      }
      next(result);
    }

    function next({ done, value }) {
      if (done) {
        return resolve(value);
      }
      return value.then(onFulfilled, onRejected);
    }
  });
  
  return { promise, cancel };
}

function* updatePersonalCircumstances() {
  const data = yield fetchData();
  const userData = yield updateUserData(data);
  const userAddress = yield updateUserAddress(userData);
  const financialStatus = yield updateFinancialStatus(userAddress);
  
  return financialStatus;
}

const { promise, cancel } = runner(updatePersonalCircumstances);

// cancel baby!!!
cancel();</pre>
<p>调用<code>cancel</code>拒绝了承诺，但使其可取消的关键是生成器功能一直在起作用。我们可以使用<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/throw" target="_blank" rel="noopener noreferrer">生成器抛出函数</a>作为中止信号来表示取消，或者我们甚至可以使用<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return" target="_blank" rel="noopener noreferrer">生成器的返回函数</a>来停止执行承诺链。</p>
<pre>cancel = () =&gt; {
  cancelled = true;
  reject({ reason: 'cancelled' });
};</pre>
<p>我在这里提出的观点是，在整个调用序列中，生成器总是在起作用，而在<code>async...await</code>中没有这样的便利。</p>
<p>现实世界中的发电机</p>
<h2>我已经创建了<a href="https://codesandbox.io/s/use-abort-f5kbt?file=/src/useAbortable/useAbortable.ts" target="_blank" rel="noopener noreferrer">这个更复杂的代码沙箱</a>，它将这个功能封装到一个<a href="https://reactjs.org/docs/hooks-reference.html" target="_blank" rel="noopener noreferrer"> React钩子</a>中。我还使用了<a href="https://github.com/davidkpiano/xstate" target="_blank" rel="noopener noreferrer"> xstate </a>来表示异步请求中的各种状态变化。使用有限状态机给了代码一个更好的抽象，并且优于伪阻塞范例，伪阻塞范例有明显的局限性，比如本文的反面角色，即<code>async...await</code>。</h2>
<p>效果. js</p>
<h2>我要感谢前端人员让我看到了JavaScript生成器这块未开采的金子。天空是无限的，它们可以用在任何可以想象的环境中，比如构建工具:</h2>
<p>查看<a href="https://github.com/thefrontside/effection/tree/master" target="_blank" rel="noopener noreferrer">效果</a>来改变你的观点。</p>
<pre>import { createConnection, Connection, ConnectionConfig } from 'mysql';
import { spawn, timeout, Operation } from 'effection';
import { main } from '@effection/node';

import { Deferred } from './deferred';

main(function* prepare(): Operation&lt;void&gt; {

  let connection: Connection = yield function* getConnection(): Operation&lt;Connection&gt; {
    // asynchronously wait for 10s and then raise an exception.
    // if a connection is created before the timeout, then this
    // operation will be cancelled automatically because the enclosing
    // operation returned.
    yield spawn(function*(): Operation&lt;void&gt; {
      yield timeout(10000);
      throw new Error('timeout out waiting 10s for mysql connection');
    });

    // Loop "forever" trying to repeatedly create a connection. Of
    // course it isn't forever, because this loop is racing against
    // the timeout.
    while (true) {
      try {
        return yield connect({
          user: "root",
          host: "localhost",
          port: 3306
        });
      } catch (error) {
        // if its a socket error or a MysqlError, we want to try again
        // otherwise, raise the exception
        if (!error.errno) {
          throw error;
        }
      }
    }
  }

  try {
    //now we have the connection and can query, migrate, etc...
  } finally {
    connection.destroy();
  }
});


/**
 * Create a mysql connection as an effection Operation.
 */
function* connect(config: ConnectionConfig): Operation&lt;Connection&gt; {
  let { resolve, reject, promise } = Deferred&lt;Connection&gt;();
  let connection = createConnection(config);

  connection.connect((err?: Error) =&gt; {
    if (err) {
      reject(err);
    } else {
      resolve(connection);
    }
  });

  return yield promise;
}</pre>
<p>收场白</p>
<h2>我认为我们已经满足于方便而不是功能。我仍然使用<code>async..await</code>,它非常适合一次调用的场景，但是我和许多其他人发现，它对于更复杂的现实情况来说是最小的。</h2>
<p>使用<a class="signup" href="https://lp.logrocket.com/blg/signup" target="_blank" rel="noopener noreferrer"> LogRocket </a>消除传统错误报告的干扰</p><div class="code-block code-block-2">
<div class="blog-plug base-cta"><h2><a href="https://lp.logrocket.com/blg/signup" target="_blank" rel="noopener noreferrer"> LogRocket </a>是一个数字体验分析解决方案，它可以保护您免受数百个假阳性错误警报的影响，只针对几个真正重要的项目。LogRocket会告诉您应用程序中实际影响用户的最具影响力的bug和UX问题。</h2>
<a href="https://lp.logrocket.com/blg/signup" class="signup" target="_blank" rel="noopener noreferrer"><img class="alignnone size-full wp-image-46 jetpack-lazy-image" src="../Images/d6f5a5dd739296c1dd7aab3d5e77eeb9.png" alt="LogRocket Dashboard Free Trial Banner" data-lazy-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png?is-pending-load=1" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-original-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png"/><noscript><img data-lazy-fallback="1" class="alignnone size-full wp-image-46" src="../Images/d6f5a5dd739296c1dd7aab3d5e77eeb9.png" alt="LogRocket Dashboard Free Trial Banner" data-original-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png"/></noscript></a>
<p>然后，使用具有深层技术遥测的会话重放来确切地查看用户看到了什么以及是什么导致了问题，就像你在他们身后看一样。</p>
<p>LogRocket自动聚合客户端错误、JS异常、前端性能指标和用户交互。然后LogRocket使用机器学习来告诉你哪些问题正在影响大多数用户，并提供你需要修复它的上下文。</p>
<p>关注重要的bug—<a class="signup" href="https://lp.logrocket.com/blg/signup-issue-free" target="_blank" rel="noopener noreferrer">今天就试试LogRocket】。</a></p>
<p>Focus on the bugs that matter — <a class="signup" href="https://lp.logrocket.com/blg/signup-issue-free" target="_blank" rel="noopener noreferrer">try LogRocket today</a>.</p></div></div>

<p class="clearfix"/>
<p class="clearfix"/>
</article>

</div>    
</body>
</html>